name: thi_trac_nghiem
description: Thi Trắc Nghiệm

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^3.1.0
  cupertino_icons: ^0.1.2
  speech_recognition: ^0.3.0+1
  scoped_model: ^0.3.0
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'
  font_awesome_flutter: ^8.2.0
  url_launcher: ^4.0.1
  shared_preferences: ^0.4.3
  toast: ^0.1.3
  flutter_secure_storage: ^3.2.1+1
  json_annotation: ^2.0.0
  rxdart: ^0.20.0
  http: ^0.12.0+2
  synchronized: ^2.1.0+1

  english_words: ^3.1.3
  flutter_search_panel: ^1.0.1
  floating_search_bar: ^0.2.0

  states_rebuilder: ^1.3.2
  flutter_custom_clippers: ^0.1.6
  html_unescape: ^1.0.1+2
  auto_size_text: ^2.0.0+2
  flip_panel: ^1.0.0



dev_dependencies:

  build_runner: ^1.0.0
  built_value_generator: ^6.1.6
  json_serializable: ^2.0.0


  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - logo.png
    - user.png
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          style: normal
        - asset: assets/fonts/Quicksand/Quicksand_Bold.otf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf

